In [50]:
import tensorflow as tf
import numpy as np

Defining Tensors

In [51]:
d0 = tf.ones((1,))
d1 = tf.ones((2,))
d2 = tf.ones((2,2))
d3 = tf.ones((2,2,2))

In [52]:
print(d3)

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


Defining constants

-> It's a simplest category of a tensor.

-> Can't change.

-> Can't be trained.

-> Can have any dimension.

In [53]:
from tensorflow import constant

# 2x3 constant
a = constant(3, shape=[2,3])

print(a.numpy())

print("---------------")

# 2x2 constant
b = constant([1,2,3,4], shape=[2,2])

print(b.numpy())

[[3 3 3]
 [3 3 3]]
---------------
[[1 2]
 [3 4]]


Other functions:

tf.zeros() -> zeros([2,2])
df.zeros_like() -> zeros_like(input_tensor) -> copies shape

similar with ones and ones_like.

tf.fill() -> fill([3,3], 7)

Defining and initializing variables

In [54]:
a0 = tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
# Could have given int16
print(a0.numpy())

[1. 2. 3. 4. 5. 6.]


In [55]:
# Defining a constant
b = tf.constant(2, tf.float32)
b.numpy()

2.0

In [56]:
# Product
c0 = tf.multiply(a0,b)
c1 = a0 * b //Same thing. OVERLOADED.

print(c0)
print('-------')
print(c1)

SyntaxError: ignored

Basic Operations in tensorflow

In [ ]:
# Add
tf.add(constant([1,2]), constant([2,3])) #Must have same shape #Element-wise

Add is overloaded so even + works.

Multiply

tf.multiply() does element wise multiplication and hence have same shape

tf.matmul() is used for matrix multlipication.

Summing over tensor dimensions

In [ ]:
A = tf.ones([2,3,4])

print(A.numpy())
print(tf.reduce_sum(A))

In [ ]:
print(tf.reduce_sum(A,0)) #Summing 0D
# Sum is still 24.

In [57]:
print(tf.reduce_sum(A,1)) #1D

tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(2, 4), dtype=float32)


In [58]:
print(tf.reduce_sum(A,2)) #2D

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)


Advanced Operations

gradient() -> Calculates the slope of a function at a point.

reshape() -> Reshapes a tensor.

random() -> Populates tensor with entries from a probability distribution.

## Finding the optimum

We might need to find:
Minimum: Lowest value of a loss function.

Maximum: Highest value of objective function.

gradient() is used in such scenarios.

Optimum: Where gradient = 0

Minimum: Change in gradient > 0 

Maximum: Change in gradient < 0

In [69]:
# Define x

x = tf.Variable(-1,0, dtype=tf.float64)
# 0 Dimensional Variable here.
# Also could be written like this:
# x = tf.Variable(-1.0) :p
# Its float to avoid warnings.

# Define y within instance of GradientTape

with tf.GradientTape() as tape:
  tape.watch(x)
  y = tf.multiply(x,x) # y = x^2
  # Computing the rate of change of y with respect to x.

  # Evaluate the gradient of y at x = -1
  g = tape.gradient(y,x) #dy/dx is stored in g
  print(g.numpy())

#Slope/Derivative is -2 at x is -1.

-2.0


Reference for Gradient Tape: https://youtu.be/tDG52BjkGUY

Reshaping a random grayscale image

In [70]:
gray = tf.random.uniform([2,2], maxval=255, dtype='int32')

In [71]:
gray

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[178, 170],
       [170,   2]], dtype=int32)>

In [72]:
gray = tf.reshape(gray,[2*2,1])

In [73]:
gray

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[178],
       [170],
       [170],
       [  2]], dtype=int32)>

In [74]:
# For a colored image,

#color = tf.random.uniform([2,2,3]....bla bla bla)

#The thing to care abou here is the shape.